// Curated team nicknames (the popular Spitznamen) per team code. Seeded defaults — an
// admin can override any of these later (stored in the DB, merged over this map). Keep
// keys in sync with TEAMS in src/data.js. A missing entry just shows no nickname line.
export const NICKNAMES = {
  MEX: "El Tri",
  RSA: "Bafana Bafana",
  KOR: "Taegeuk Warriors",
  CZE: "Národní tým",
  CAN: "Les Rouges",
  BIH: "Zmajevi",
  QAT: "Al Annabi",
  SUI: "Nati",
  BRA: "Seleção",
  MAR: "Lions de l'Atlas",
  HAI: "Les Grenadiers",
  SCO: "Bravehearts",
  USA: "Stars and Stripes",
  PAR: "La Albirroja",
  AUS: "Socceroos",
  TUR: "Ay-Yıldızlılar",
  GER: "Die Mannschaft",
  CUW: "La Familia Azul",
  CIV: "Les Éléphants",
  ECU: "La Tri",
  NED: "Oranje",
  JPN: "Samurai Blue",
  SWE: "Blågult",
  TUN: "Aigles de Carthage",
  BEL: "Rode Duivels",
  EGY: "The Pharaohs",
  IRN: "Team Melli",
  NZL: "All Whites",
  ESP: "La Roja",
  CPV: "Tubarões Azuis",
  KSA: "Green Falcons",
  URU: "La Celeste",
  FRA: "Les Bleus",
  SEN: "Lions de la Téranga",
  IRQ: "Lions of Mesopotamia",
  NOR: "Løvene",
  ARG: "La Albiceleste",
  ALG: "Les Fennecs",
  AUT: "Unsere Burschen",
  JOR: "Al-Nashama",
  POR: "A Seleção",
  COD: "Les Léopards",
  UZB: "White Wolves",
  COL: "Los Cafeteros",
  ENG: "Three Lions",
  CRO: "Vatreni",
  GHA: "Black Stars",
  PAN: "La Marea Roja",
};
